listen: :8443

tls:
  cert: /root/certs/fullchain.pem
  key: /root/certs/privkey.pem

bandwidth:
  up: 300 mbps
  down: 100 mbps

auth:
  type: password
  password: password0

resolver:
  type: https
  https:
    addr: 1.1.1.1:443
    timeout: 10s

acl:
  inline: 
    - reject(all, udp/443)
